markdown : kramdown
theme: jekyll-theme-slate
title-heading: false
name: SM Portfolio
title: "Welcome to Sarvesh Meenowa's Portfolio"
github:
  is_project_page: false
 
lang: en 
languages: ["en", "fr"] 
plugins:
  - jemoji
